# C compiler options
CFLAGS += -Wall -Werror -std=c89 -ansi -Wpedantic
# -Wall -Wextra -std=c89 -pedantic -Wmissing-prototypes -Wstrict-prototypes \
#     -Wold-style-definition

# local system OS
UNAME_S := $(shell uname -s)
ifneq ($(filter CYGWIN%,$(UNAME_S)),)
	OPER := cygwin
endif
ifeq ($(UNAME_S),Darwin)
	OPER := darwin
endif
ifeq ($(UNAME_S),Linux)
	OPER := linux
endif
ifneq ($(filter MINGW%,$(UNAME_S)),)
	OPER := mingw
endif

# local processor architecture
UNAME_M := $(shell uname -m)
PROC := $(UNAME_M)
ifeq (${OPER},linux)
ifeq (${PROC},x86_64)
ifeq ($(shell getconf LONG_BIT),32)
	PROC := i686
endif
endif
endif

# local system
SYSTEM := $(OPER)-$(PROC)

# default build is local system platform
TARGET := $(SYSTEM)

# local system target executables
DISC := $(SYSTEM)/disc
ORTER := $(SYSTEM)/orter
ORTERFORTH := $(SYSTEM)/orterforth

# system dependent command to get file size
ifeq ($(OPER),cygwin)
STAT := stat -c %s
endif
ifeq ($(OPER),darwin)
STAT := stat -f%z
endif
ifeq ($(OPER),linux)
STAT := stat -c %s
endif

# serial port
ifeq ($(OPER),cygwin)
SERIALPORT := /dev/ttyS2
endif
ifeq ($(OPER),darwin)
SERIALPORT := /dev/cu.usbserial-FT2XIBOF
endif
ifeq ($(OPER),linux)
SERIALPORT := /dev/ttyUSB0
endif
SERIALBAUD := 9600

# default target
.PHONY : default
default : build

# local disc server executable
$(DISC) : \
	$(SYSTEM)/orter_io.o \
	$(SYSTEM)/orter_serial.o \
	$(SYSTEM)/orter_spectrum.o \
	$(SYSTEM)/persci.o \
	disc.c

	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ $^

# orter - retrocomputing multitool
$(ORTER) : \
	$(SYSTEM)/orter_bbc.o \
	$(SYSTEM)/orter_io.o \
	$(SYSTEM)/orter_ql.o \
	$(SYSTEM)/orter_serial.o \
	$(SYSTEM)/orter_spectrum.o \
	orter/main.c

	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ $^


# === LOCAL SYSTEM ===

# SYSTEMOPTION := assembly
SYSTEMOPTION := default

SYSTEMDEPS := \
	$(SYSTEM)/inst.o \
	$(SYSTEM)/persci.o \
	$(SYSTEM)/rf.o \
	$(SYSTEM)/system.o

# local system assembly option config:
ifeq ($(SYSTEMOPTION),assembly)
# add the assembly code to deps
SYSTEMDEPS += $(SYSTEM)/rf_$(PROC).o
# tell C code it is there
CPPFLAGS += -DRF_ASSEMBLY
# reconcile leading underscore handling
ifeq ($(OPER),cygwin)
LDFLAGS += -t gcc.ld
endif
ifeq ($(OPER),linux)
LDFLAGS += -t gcc.ld
endif
endif

# local system executable
$(ORTERFORTH) : \
	$(SYSTEMDEPS) \
	main.c

	$(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) -o $@ $^

# local system build dir
$(SYSTEM) :

	mkdir $@

# all local system executables
.PHONY : $(SYSTEM)-build
$(SYSTEM)-build : \
	$(DISC) \
	$(ORTER) \
	$(ORTERFORTH)

# clean local system build
.PHONY : $(SYSTEM)-clean
$(SYSTEM)-clean :

	rm -rf $(SYSTEM)/*
	rm -f model.img
	rm -f model.inc

# default example
EXAMPLE=test

# run local build with example disc
.PHONY : $(SYSTEM)-example
$(SYSTEM)-example : $(ORTERFORTH) example/$(EXAMPLE).img

	echo "EMPTY-BUFFERS 1 LOAD" | $< example/$(EXAMPLE).img

# runtime disc images
DR0=messages.img
DR1=data.img

# run local build
.PHONY : $(SYSTEM)-run
$(SYSTEM)-run : $(ORTERFORTH) $(DR0) $(DR1)

	@$< $(DR0) $(DR1)

# for analysing assembly code generated by the C compiler
$(SYSTEM)/%.s : %.c | $(SYSTEM)

	$(CC) -S $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# inst lib
$(SYSTEM)/inst.o : inst.c model.inc rf.h system.inc persci.h | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# orter libs - BBC Micro
$(SYSTEM)/orter_bbc.o : orter/bbc.c | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# orter libs - nonblocking I/O utilities
$(SYSTEM)/orter_io.o : orter/io.c orter/io.h | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# orter libs - Sinclair QL
$(SYSTEM)/orter_ql.o : orter/ql.c | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# orter libs - serial port handling
$(SYSTEM)/orter_serial.o : orter/serial.c orter/io.h orter/serial.h | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# orter libs - Sinclair ZX Spectrum
$(SYSTEM)/orter_spectrum.o : orter/spectrum.c | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# disc impl lib
$(SYSTEM)/persci.o : persci.c persci.h | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# C code lib
$(SYSTEM)/rf.o : rf.c rf.h system.inc | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# assembly code lib
$(SYSTEM)/rf_$(PROC).o : rf_$(PROC).s | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -DRF_OPER=$(OPER) -c -o $@ $<

# system dependent code lib
$(SYSTEM)/system.o : system.c rf.h system.inc persci.h | $(SYSTEM)

	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

# help
.PHONY : $(TARGET)-help
$(TARGET)-help :

	@if [ "$(TARGET)" = "$(SYSTEM)" ] ; then more help.txt ; else more target/$(TARGET)/help.txt ; fi

# disc images from %.f files including model.f
%.img : %.f | $(DISC)

	$(DISC) create < $< > $@.io
	mv $@.io $@

# common inst script commands
CHECKMEMORY := printf '* \033[1;33mChecking memory limits\033[0;0m\n' ; sh scripts/check-memory.sh
STARTDISC := printf '* \033[1;33mStarting disc\033[0;0m\n' ; sh scripts/start.sh /dev/stdin /dev/stdout disc.pid $(DISC)
STARTDISCTCP := $(STARTDISC) tcp 5705
STOPDISC := printf '* \033[1;33mStopping disc\033[0;0m\n' ; sh scripts/stop.sh disc.pid
STARTMAME := printf '* \033[1;33mStarting MAME\033[0;0m\n' ; sh scripts/start.sh /dev/stdin /dev/stdout mame.pid mame
STOPMAME := printf '* \033[1;33mStopping MAME\033[0;0m\n' ; sh scripts/stop.sh mame.pid
WAITUNTILSAVED := printf '* \033[1;33mWaiting until saved\033[0;0m\n' ; sh scripts/wait-until-saved.sh

# common options for MAME
MAMEOPTS := -rompath roms -video opengl -skip_gameinfo -nomax -window

# build
.PHONY : build
build : $(TARGET)-build

include target/bbc/bbc.mk

include target/c64/c64.mk

# clean
.PHONY : clean
clean : $(TARGET)-clean

# create empty to use as default DR1
data.img :

	touch $@

# run disc on physical serial port
.PHONY : disc
disc : $(DISC) $(DR0) $(DR1)

	$(DISC) serial $(SERIALPORT) $(SERIALBAUD) $(DR0) $(DR1)

include target/dragon/dragon.mk

# run an example program
.PHONY : example
example : $(TARGET)-example

# help
.PHONY : help
help : $(TARGET)-help

# install to local
.PHONY : install
install : $(ORTER) $(ORTERFORTH)

	cp "$(ORTER)" /usr/local/bin/orter
	cp "$(ORTERFORTH)" /usr/local/bin/orterforth

include target/m100/m100.mk

# disc image as C include
model.inc : model.img | $(ORTER)

	# xxd -i $< > $@.io
	$(ORTER) hex include model_disc < $< > $@.io
	mv $@.io $@

include target/pico/pico.mk

include target/ql/ql.mk

include target/rc2014/rc2014.mk

# Raspberry Pi 1 - armv6l assembly source is (currently) the same as armv7l
rf_armv6l.s : rf_armv7l.s

	cp -p $< $@

# ROM file dir
roms : 

	mkdir $@

# run local build
.PHONY : run
run : $(TARGET)-run

# run working script
.PHONY : script
script :

	@[ -f scripts/script.sh ] || (echo "Create the file scripts/script.sh for your working script and run it using: make script" && exit 1)
	sh scripts/script.sh

include target/spectrum/spectrum.mk

tools :

	mkdir $@

# uninstall from local
.PHONY : uninstall
uninstall :

	rm -f /usr/local/bin/orter
	rm -f /usr/local/bin/orterforth

include target/z88/z88.mk

include target/zx81/zx81.mk
