#!/usr/bin/env sh

set -eu

# wait for the terminating block to be written to the disc
while ! grep ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ 1.disc; do
  # echo "waiting for Zs"
  sleep 1
done

echo "terminating block written"
